
import * as _ from 'lodash';
import { FilterableMapCollection } from '@ts-core/common';
import { Zodiac, Zodiacs } from './Zodiacs';
import { ZodiacDecanSpirit } from './ZodiacDecanSpirits';
import { Genius } from './Geniuses';
import { Demon } from './Demons';
import { Entity } from './IEntity';
import { DayTimeRange, ITimeRange } from './TimeRange';

export type ZodiacAngleSpiritName = string;

export class ZodiacAngleSpirit extends Entity<ZodiacAngleSpiritName> {
    //--------------------------------------------------------------------------
    //
    // 	Properties
    //
    //--------------------------------------------------------------------------

    public degree: string;
    public timeRange: ITimeRange;

    public demon: Demon;
    public zodiac: Zodiac;
    public genius: Genius;
    public decanSpirit: ZodiacDecanSpirit;

    //--------------------------------------------------------------------------
    //
    // 	Constructor
    //
    //--------------------------------------------------------------------------

    constructor(name: ZodiacAngleSpiritName | number, timeRange: ITimeRange) {
        super(name.toString());
        this.timeRange = timeRange;
    }
}

export class ZodiacAngleSpirits extends FilterableMapCollection<ZodiacAngleSpirit> {
    //--------------------------------------------------------------------------
    //
    // 	Constructor
    //
    //--------------------------------------------------------------------------

    constructor(zodiacs: Zodiacs) {
        super('name');

        let timeRanges = [
            new DayTimeRange({ date: 21, month: 2 }, { date: 22, month: 2 }),
            new DayTimeRange({ date: 22, month: 2 }, { date: 23, month: 2 }),
            new DayTimeRange({ date: 23, month: 2 }, { date: 24, month: 2 }),
            new DayTimeRange({ date: 24, month: 2 }, { date: 25, month: 2 }),
            new DayTimeRange({ date: 25, month: 2 }, { date: 26, month: 2 }),
            new DayTimeRange({ date: 26, month: 2 }, { date: 27, month: 2 }),
            new DayTimeRange({ date: 27, month: 2 }, { date: 28, month: 2 }),
            new DayTimeRange({ date: 28, month: 2 }, { date: 29, month: 2 }),
            new DayTimeRange({ date: 29, month: 2 }, { date: 30, month: 2 }),
            new DayTimeRange({ date: 30, month: 2 }, { date: 31, month: 2 }),
            new DayTimeRange({ date: 31, month: 2 }, { date: 1, month: 3 }),
            new DayTimeRange({ date: 1, month: 3 }, { date: 2, month: 3 }),
            new DayTimeRange({ date: 2, month: 3 }, { date: 3, month: 3 }),
            new DayTimeRange({ date: 3, month: 3 }, { date: 4, month: 3 }),
            new DayTimeRange({ date: 4, month: 3 }, { date: 5, month: 3 }),
            new DayTimeRange({ date: 5, month: 3 }, { date: 6, month: 3 }),
            new DayTimeRange({ date: 6, month: 3 }, { date: 7, month: 3 }),
            new DayTimeRange({ date: 7, month: 3 }, { date: 8, month: 3 }),
            new DayTimeRange({ date: 8, month: 3 }, { date: 9, month: 3 }),
            new DayTimeRange({ date: 9, month: 3 }, { date: 10, month: 3 }),
            new DayTimeRange({ date: 10, month: 3 }, { date: 11, month: 3 }),
            new DayTimeRange({ date: 11, month: 3 }, { date: 12, month: 3 }),
            new DayTimeRange({ date: 12, month: 3 }, { date: 13, month: 3 }),
            new DayTimeRange({ date: 13, month: 3 }, { date: 14, month: 3 }),
            new DayTimeRange({ date: 14, month: 3 }, { date: 15, month: 3 }),
            new DayTimeRange({ date: 15, month: 3 }, { date: 16, month: 3 }),
            new DayTimeRange({ date: 16, month: 3 }, { date: 17, month: 3 }),
            new DayTimeRange({ date: 17, month: 3 }, { date: 18, month: 3 }),
            new DayTimeRange({ date: 18, month: 3 }, { date: 19, month: 3 }),
            new DayTimeRange({ date: 19, month: 3 }, { date: 20, month: 3 }),

            new DayTimeRange({ date: 21, month: 3 }, { date: 22, month: 3 }),
            new DayTimeRange({ date: 22, month: 3 }, { date: 23, month: 3 }),
            new DayTimeRange({ date: 23, month: 3 }, { date: 24, month: 3 }),
            new DayTimeRange({ date: 24, month: 3 }, { date: 25, month: 3 }),
            new DayTimeRange({ date: 25, month: 3 }, { date: 26, month: 3 }),
            new DayTimeRange({ date: 26, month: 3 }, { date: 27, month: 3 }),
            new DayTimeRange({ date: 27, month: 3 }, { date: 28, month: 3 }),
            new DayTimeRange({ date: 28, month: 3 }, { date: 29, month: 3 }),
            new DayTimeRange({ date: 29, month: 3 }, { date: 30, month: 3 }),
            new DayTimeRange({ date: 30, month: 3 }, { date: 1, month: 4 }),
            new DayTimeRange({ date: 1, month: 4 }, { date: 2, month: 4 }),
            new DayTimeRange({ date: 2, month: 4 }, { date: 3, month: 4 }),
            new DayTimeRange({ date: 3, month: 4 }, { date: 4, month: 4 }),
            new DayTimeRange({ date: 4, month: 4 }, { date: 5, month: 4 }),
            new DayTimeRange({ date: 5, month: 4 }, { date: 6, month: 4 }),
            new DayTimeRange({ date: 6, month: 4 }, { date: 7, month: 4 }),
            new DayTimeRange({ date: 7, month: 4 }, { date: 8, month: 4 }),
            new DayTimeRange({ date: 8, month: 4 }, { date: 9, month: 4 }),
            new DayTimeRange({ date: 9, month: 4 }, { date: 10, month: 4 }),
            new DayTimeRange({ date: 10, month: 4 }, { date: 11, month: 4 }),
            new DayTimeRange({ date: 11, month: 4 }, { date: 12, month: 4 }),
            new DayTimeRange({ date: 12, month: 4 }, { date: 13, month: 4 }),
            new DayTimeRange({ date: 13, month: 4 }, { date: 14, month: 4 }),
            new DayTimeRange({ date: 14, month: 4 }, { date: 15, month: 4 }),
            new DayTimeRange({ date: 15, month: 4 }, { date: 16, month: 4 }),
            new DayTimeRange({ date: 16, month: 4 }, { date: 17, month: 4 }),
            new DayTimeRange({ date: 17, month: 4 }, { date: 18, month: 4 }),
            new DayTimeRange({ date: 18, month: 4 }, { date: 19, month: 4 }),
            new DayTimeRange({ date: 19, month: 4 }, { date: 20, month: 4 }),
            new DayTimeRange({ date: 20, month: 4 }, { date: 21, month: 4 }),

            new DayTimeRange({ date: 22, month: 4 }, { date: 23, month: 4 }),
            new DayTimeRange({ date: 23, month: 4 }, { date: 24, month: 4 }),
            new DayTimeRange({ date: 24, month: 4 }, { date: 25, month: 4 }),
            new DayTimeRange({ date: 25, month: 4 }, { date: 26, month: 4 }),
            new DayTimeRange({ date: 26, month: 4 }, { date: 27, month: 4 }),
            new DayTimeRange({ date: 27, month: 4 }, { date: 28, month: 4 }),
            new DayTimeRange({ date: 28, month: 4 }, { date: 29, month: 4 }),
            new DayTimeRange({ date: 29, month: 4 }, { date: 30, month: 4 }),
            new DayTimeRange({ date: 30, month: 4 }, { date: 31, month: 4 }),
            new DayTimeRange({ date: 31, month: 4 }, { date: 1, month: 5 }),
            new DayTimeRange({ date: 1, month: 5 }, { date: 2, month: 5 }),
            new DayTimeRange({ date: 2, month: 5 }, { date: 3, month: 5 }),
            new DayTimeRange({ date: 3, month: 5 }, { date: 4, month: 5 }),
            new DayTimeRange({ date: 4, month: 5 }, { date: 5, month: 5 }),
            new DayTimeRange({ date: 5, month: 5 }, { date: 6, month: 5 }),
            new DayTimeRange({ date: 6, month: 5 }, { date: 7, month: 5 }),
            new DayTimeRange({ date: 7, month: 5 }, { date: 8, month: 5 }),
            new DayTimeRange({ date: 8, month: 5 }, { date: 9, month: 5 }),
            new DayTimeRange({ date: 9, month: 5 }, { date: 10, month: 5 }),
            new DayTimeRange({ date: 10, month: 5 }, { date: 11, month: 5 }),
            new DayTimeRange({ date: 11, month: 5 }, { date: 12, month: 5 }),
            new DayTimeRange({ date: 12, month: 5 }, { date: 13, month: 5 }),
            new DayTimeRange({ date: 13, month: 5 }, { date: 14, month: 5 }),
            new DayTimeRange({ date: 14, month: 5 }, { date: 15, month: 5 }),
            new DayTimeRange({ date: 15, month: 5 }, { date: 16, month: 5 }),
            new DayTimeRange({ date: 16, month: 5 }, { date: 17, month: 5 }),
            new DayTimeRange({ date: 17, month: 5 }, { date: 18, month: 5 }),
            new DayTimeRange({ date: 18, month: 5 }, { date: 19, month: 5 }),
            new DayTimeRange({ date: 19, month: 5 }, { date: 20, month: 5 }),
            new DayTimeRange({ date: 20, month: 5 }, { date: 21, month: 5 }),

            new DayTimeRange({ date: 22, month: 5 }, { date: 23, month: 5 }),
            new DayTimeRange({ date: 23, month: 5 }, { date: 24, month: 5 }),
            new DayTimeRange({ date: 24, month: 5 }, { date: 25, month: 5 }),
            new DayTimeRange({ date: 25, month: 5 }, { date: 26, month: 5 }),
            new DayTimeRange({ date: 26, month: 5 }, { date: 27, month: 5 }),
            new DayTimeRange({ date: 27, month: 5 }, { date: 28, month: 5 }),
            new DayTimeRange({ date: 28, month: 5 }, { date: 29, month: 5 }),
            new DayTimeRange({ date: 29, month: 5 }, { date: 30, month: 5 }),
            new DayTimeRange({ date: 30, month: 5 }, { date: 31, month: 5 }),
            new DayTimeRange({ date: 31, month: 5 }, { date: 1, month: 6 }),
            new DayTimeRange({ date: 1, month: 6 }, { date: 2, month: 6 }),
            new DayTimeRange({ date: 2, month: 6 }, { date: 3, month: 6 }),
            new DayTimeRange({ date: 3, month: 6 }, { date: 4, month: 6 }),
            new DayTimeRange({ date: 4, month: 6 }, { date: 5, month: 6 }),
            new DayTimeRange({ date: 5, month: 6 }, { date: 6, month: 6 }),
            new DayTimeRange({ date: 6, month: 6 }, { date: 7, month: 6 }),
            new DayTimeRange({ date: 7, month: 6 }, { date: 8, month: 6 }),
            new DayTimeRange({ date: 8, month: 6 }, { date: 9, month: 6 }),
            new DayTimeRange({ date: 9, month: 6 }, { date: 10, month: 6 }),
            new DayTimeRange({ date: 10, month: 6 }, { date: 11, month: 6 }),
            new DayTimeRange({ date: 11, month: 6 }, { date: 12, month: 6 }),
            new DayTimeRange({ date: 12, month: 6 }, { date: 13, month: 6 }),
            new DayTimeRange({ date: 13, month: 6 }, { date: 14, month: 6 }),
            new DayTimeRange({ date: 14, month: 6 }, { date: 15, month: 6 }),
            new DayTimeRange({ date: 15, month: 6 }, { date: 16, month: 6 }),
            new DayTimeRange({ date: 16, month: 6 }, { date: 17, month: 6 }),
            new DayTimeRange({ date: 17, month: 6 }, { date: 18, month: 6 }),
            new DayTimeRange({ date: 18, month: 6 }, { date: 19, month: 6 }),
            new DayTimeRange({ date: 19, month: 6 }, { date: 20, month: 6 }),
            new DayTimeRange({ date: 20, month: 6 }, { date: 21, month: 6 }),
            new DayTimeRange({ date: 21, month: 6 }, { date: 22, month: 6 }),
            new DayTimeRange({ date: 22, month: 6 }, { date: 23, month: 6 }),
            new DayTimeRange({ date: 23, month: 6 }, { date: 24, month: 6 }),
            new DayTimeRange({ date: 24, month: 6 }, { date: 25, month: 6 }),
            new DayTimeRange({ date: 25, month: 6 }, { date: 26, month: 6 }),
            new DayTimeRange({ date: 26, month: 6 }, { date: 27, month: 6 }),
            new DayTimeRange({ date: 27, month: 6 }, { date: 28, month: 6 }),
            new DayTimeRange({ date: 28, month: 6 }, { date: 29, month: 6 }),
            new DayTimeRange({ date: 29, month: 6 }, { date: 30, month: 6 }),
            new DayTimeRange({ date: 30, month: 6 }, { date: 31, month: 6 }),
            new DayTimeRange({ date: 31, month: 6 }, { date: 1, month: 7 }),
            new DayTimeRange({ date: 1, month: 7 }, { date: 2, month: 7 }),
            new DayTimeRange({ date: 2, month: 7 }, { date: 3, month: 7 }),
            new DayTimeRange({ date: 3, month: 7 }, { date: 4, month: 7 }),
            new DayTimeRange({ date: 4, month: 7 }, { date: 5, month: 7 }),
            new DayTimeRange({ date: 5, month: 7 }, { date: 6, month: 7 }),
            new DayTimeRange({ date: 6, month: 7 }, { date: 7, month: 7 }),
            new DayTimeRange({ date: 7, month: 7 }, { date: 8, month: 7 }),
            new DayTimeRange({ date: 8, month: 7 }, { date: 9, month: 7 }),
            new DayTimeRange({ date: 9, month: 7 }, { date: 10, month: 7 }),
            new DayTimeRange({ date: 10, month: 7 }, { date: 11, month: 7 }),
            new DayTimeRange({ date: 11, month: 7 }, { date: 12, month: 7 }),
            new DayTimeRange({ date: 12, month: 7 }, { date: 13, month: 7 }),
            new DayTimeRange({ date: 13, month: 7 }, { date: 14, month: 7 }),
            new DayTimeRange({ date: 14, month: 7 }, { date: 15, month: 7 }),
            new DayTimeRange({ date: 15, month: 7 }, { date: 16, month: 7 }),
            new DayTimeRange({ date: 16, month: 7 }, { date: 17, month: 7 }),
            new DayTimeRange({ date: 17, month: 7 }, { date: 18, month: 7 }),
            new DayTimeRange({ date: 18, month: 7 }, { date: 19, month: 7 }),
            new DayTimeRange({ date: 19, month: 7 }, { date: 20, month: 7 }),
            new DayTimeRange({ date: 20, month: 7 }, { date: 21, month: 7 }),
            new DayTimeRange({ date: 21, month: 7 }, { date: 22, month: 7 }),
            new DayTimeRange({ date: 22, month: 7 }, { date: 23, month: 7 }),
            new DayTimeRange({ date: 24, month: 7 }, { date: 25, month: 7 }),
            new DayTimeRange({ date: 25, month: 7 }, { date: 26, month: 7 }),
            new DayTimeRange({ date: 26, month: 7 }, { date: 27, month: 7 }),
            new DayTimeRange({ date: 27, month: 7 }, { date: 28, month: 7 }),
            new DayTimeRange({ date: 28, month: 7 }, { date: 29, month: 7 }),
            new DayTimeRange({ date: 29, month: 7 }, { date: 30, month: 7 }),
            new DayTimeRange({ date: 30, month: 7 }, { date: 31, month: 7 }),
            new DayTimeRange({ date: 31, month: 7 }, { date: 1, month: 8 }),
            new DayTimeRange({ date: 1, month: 8 }, { date: 2, month: 8 }),
            new DayTimeRange({ date: 2, month: 8 }, { date: 3, month: 8 }),
            new DayTimeRange({ date: 3, month: 8 }, { date: 4, month: 8 }),
            new DayTimeRange({ date: 4, month: 8 }, { date: 5, month: 8 }),
            new DayTimeRange({ date: 5, month: 8 }, { date: 6, month: 8 }),
            new DayTimeRange({ date: 6, month: 8 }, { date: 7, month: 8 }),
            new DayTimeRange({ date: 7, month: 8 }, { date: 8, month: 8 }),
            new DayTimeRange({ date: 8, month: 8 }, { date: 9, month: 8 }),
            new DayTimeRange({ date: 9, month: 8 }, { date: 10, month: 8 }),
            new DayTimeRange({ date: 10, month: 8 }, { date: 11, month: 8 }),
            new DayTimeRange({ date: 11, month: 8 }, { date: 12, month: 8 }),
            new DayTimeRange({ date: 12, month: 8 }, { date: 13, month: 8 }),
            new DayTimeRange({ date: 13, month: 8 }, { date: 14, month: 8 }),
            new DayTimeRange({ date: 14, month: 8 }, { date: 15, month: 8 }),
            new DayTimeRange({ date: 15, month: 8 }, { date: 16, month: 8 }),
            new DayTimeRange({ date: 16, month: 8 }, { date: 17, month: 8 }),
            new DayTimeRange({ date: 17, month: 8 }, { date: 18, month: 8 }),
            new DayTimeRange({ date: 18, month: 8 }, { date: 19, month: 8 }),
            new DayTimeRange({ date: 19, month: 8 }, { date: 20, month: 8 }),
            new DayTimeRange({ date: 20, month: 8 }, { date: 21, month: 8 }),
            new DayTimeRange({ date: 21, month: 8 }, { date: 22, month: 8 }),
            new DayTimeRange({ date: 22, month: 8 }, { date: 23, month: 8 }),

            new DayTimeRange({ date: 24, month: 8 }, { date: 25, month: 8 }),
            new DayTimeRange({ date: 25, month: 8 }, { date: 26, month: 8 }),
            new DayTimeRange({ date: 26, month: 8 }, { date: 27, month: 8 }),
            new DayTimeRange({ date: 27, month: 8 }, { date: 28, month: 8 }),
            new DayTimeRange({ date: 28, month: 8 }, { date: 29, month: 8 }),
            new DayTimeRange({ date: 29, month: 8 }, { date: 30, month: 8 }),
            new DayTimeRange({ date: 30, month: 8 }, { date: 1, month: 9 }),
            new DayTimeRange({ date: 1, month: 9 }, { date: 2, month: 9 }),
            new DayTimeRange({ date: 2, month: 9 }, { date: 3, month: 9 }),
            new DayTimeRange({ date: 3, month: 9 }, { date: 4, month: 9 }),
            new DayTimeRange({ date: 4, month: 9 }, { date: 5, month: 9 }),
            new DayTimeRange({ date: 5, month: 9 }, { date: 6, month: 9 }),
            new DayTimeRange({ date: 6, month: 9 }, { date: 7, month: 9 }),
            new DayTimeRange({ date: 7, month: 9 }, { date: 8, month: 9 }),
            new DayTimeRange({ date: 8, month: 9 }, { date: 9, month: 9 }),
            new DayTimeRange({ date: 9, month: 9 }, { date: 10, month: 9 }),
            new DayTimeRange({ date: 10, month: 9 }, { date: 11, month: 9 }),
            new DayTimeRange({ date: 11, month: 9 }, { date: 12, month: 9 }),
            new DayTimeRange({ date: 12, month: 9 }, { date: 13, month: 9 }),
            new DayTimeRange({ date: 13, month: 9 }, { date: 14, month: 9 }),
            new DayTimeRange({ date: 14, month: 9 }, { date: 15, month: 9 }),
            new DayTimeRange({ date: 15, month: 9 }, { date: 16, month: 9 }),
            new DayTimeRange({ date: 16, month: 9 }, { date: 17, month: 9 }),
            new DayTimeRange({ date: 17, month: 9 }, { date: 18, month: 9 }),
            new DayTimeRange({ date: 18, month: 9 }, { date: 19, month: 9 }),
            new DayTimeRange({ date: 19, month: 9 }, { date: 20, month: 9 }),
            new DayTimeRange({ date: 20, month: 9 }, { date: 21, month: 9 }),
            new DayTimeRange({ date: 21, month: 9 }, { date: 22, month: 9 }),
            new DayTimeRange({ date: 22, month: 9 }, { date: 23, month: 9 }),
            new DayTimeRange({ date: 23, month: 9 }, { date: 24, month: 9 }),
            new DayTimeRange({ date: 24, month: 9 }, { date: 25, month: 9 }),
            new DayTimeRange({ date: 25, month: 9 }, { date: 26, month: 9 }),
            new DayTimeRange({ date: 26, month: 9 }, { date: 27, month: 9 }),
            new DayTimeRange({ date: 27, month: 9 }, { date: 28, month: 9 }),
            new DayTimeRange({ date: 28, month: 9 }, { date: 29, month: 9 }),
            new DayTimeRange({ date: 29, month: 9 }, { date: 30, month: 9 }),
            new DayTimeRange({ date: 30, month: 9 }, { date: 31, month: 9 }),
            new DayTimeRange({ date: 31, month: 9 }, { date: 1, month: 10 }),
            new DayTimeRange({ date: 1, month: 10 }, { date: 2, month: 10 }),
            new DayTimeRange({ date: 2, month: 10 }, { date: 3, month: 10 }),
            new DayTimeRange({ date: 3, month: 10 }, { date: 4, month: 10 }),
            new DayTimeRange({ date: 4, month: 10 }, { date: 5, month: 10 }),
            new DayTimeRange({ date: 5, month: 10 }, { date: 6, month: 10 }),
            new DayTimeRange({ date: 6, month: 10 }, { date: 7, month: 10 }),
            new DayTimeRange({ date: 7, month: 10 }, { date: 8, month: 10 }),
            new DayTimeRange({ date: 8, month: 10 }, { date: 9, month: 10 }),
            new DayTimeRange({ date: 9, month: 10 }, { date: 10, month: 10 }),
            new DayTimeRange({ date: 10, month: 10 }, { date: 11, month: 10 }),
            new DayTimeRange({ date: 11, month: 10 }, { date: 12, month: 10 }),
            new DayTimeRange({ date: 12, month: 10 }, { date: 13, month: 10 }),
            new DayTimeRange({ date: 13, month: 10 }, { date: 14, month: 10 }),
            new DayTimeRange({ date: 14, month: 10 }, { date: 15, month: 10 }),
            new DayTimeRange({ date: 15, month: 10 }, { date: 16, month: 10 }),
            new DayTimeRange({ date: 16, month: 10 }, { date: 17, month: 10 }),
            new DayTimeRange({ date: 17, month: 10 }, { date: 18, month: 10 }),
            new DayTimeRange({ date: 18, month: 10 }, { date: 19, month: 10 }),
            new DayTimeRange({ date: 19, month: 10 }, { date: 20, month: 10 }),
            new DayTimeRange({ date: 20, month: 10 }, { date: 21, month: 10 }),
            new DayTimeRange({ date: 21, month: 10 }, { date: 22, month: 10 }),
            new DayTimeRange({ date: 22, month: 10 }, { date: 23, month: 10 }),
            new DayTimeRange({ date: 23, month: 10 }, { date: 24, month: 10 }),
            new DayTimeRange({ date: 24, month: 10 }, { date: 25, month: 10 }),
            new DayTimeRange({ date: 25, month: 10 }, { date: 26, month: 10 }),
            new DayTimeRange({ date: 26, month: 10 }, { date: 27, month: 10 }),
            new DayTimeRange({ date: 27, month: 10 }, { date: 28, month: 10 }),
            new DayTimeRange({ date: 28, month: 10 }, { date: 29, month: 10 }),
            new DayTimeRange({ date: 29, month: 10 }, { date: 30, month: 10 }),
            new DayTimeRange({ date: 30, month: 10 }, { date: 1, month: 11 }),
            new DayTimeRange({ date: 1, month: 11 }, { date: 2, month: 11 }),
            new DayTimeRange({ date: 2, month: 11 }, { date: 3, month: 11 }),
            new DayTimeRange({ date: 3, month: 11 }, { date: 4, month: 11 }),
            new DayTimeRange({ date: 4, month: 11 }, { date: 5, month: 11 }),
            new DayTimeRange({ date: 5, month: 11 }, { date: 6, month: 11 }),
            new DayTimeRange({ date: 6, month: 11 }, { date: 7, month: 11 }),
            new DayTimeRange({ date: 7, month: 11 }, { date: 8, month: 11 }),
            new DayTimeRange({ date: 8, month: 11 }, { date: 9, month: 11 }),
            new DayTimeRange({ date: 9, month: 11 }, { date: 10, month: 11 }),
            new DayTimeRange({ date: 10, month: 11 }, { date: 11, month: 11 }),
            new DayTimeRange({ date: 11, month: 11 }, { date: 12, month: 11 }),
            new DayTimeRange({ date: 12, month: 11 }, { date: 13, month: 11 }),
            new DayTimeRange({ date: 13, month: 11 }, { date: 14, month: 11 }),
            new DayTimeRange({ date: 14, month: 11 }, { date: 15, month: 11 }),
            new DayTimeRange({ date: 15, month: 11 }, { date: 16, month: 11 }),
            new DayTimeRange({ date: 16, month: 11 }, { date: 17, month: 11 }),
            new DayTimeRange({ date: 17, month: 11 }, { date: 18, month: 11 }),
            new DayTimeRange({ date: 18, month: 11 }, { date: 19, month: 11 }),
            new DayTimeRange({ date: 19, month: 11 }, { date: 20, month: 11 }),
            new DayTimeRange({ date: 20, month: 11 }, { date: 21, month: 11 }),
            new DayTimeRange({ date: 21, month: 11 }, { date: 22, month: 11 }),
            new DayTimeRange({ date: 22, month: 11 }, { date: 23, month: 11 }),
            new DayTimeRange({ date: 23, month: 11 }, { date: 24, month: 11 }),
            new DayTimeRange({ date: 24, month: 11 }, { date: 25, month: 11 }),
            new DayTimeRange({ date: 25, month: 11 }, { date: 26, month: 11 }),
            new DayTimeRange({ date: 26, month: 11 }, { date: 27, month: 11 }),
            new DayTimeRange({ date: 27, month: 11 }, { date: 28, month: 11 }),
            new DayTimeRange({ date: 28, month: 11 }, { date: 29, month: 11 }),
            new DayTimeRange({ date: 29, month: 11 }, { date: 30, month: 11 }),
            new DayTimeRange({ date: 30, month: 11 }, { date: 31, month: 11 }),
            new DayTimeRange({ date: 31, month: 11 }, { date: 1, month: 0 }),
            new DayTimeRange({ date: 1, month: 0 }, { date: 2, month: 0 }),
            new DayTimeRange({ date: 2, month: 0 }, { date: 3, month: 0 }),
            new DayTimeRange({ date: 3, month: 0 }, { date: 4, month: 0 }),
            new DayTimeRange({ date: 4, month: 0 }, { date: 5, month: 0 }),
            new DayTimeRange({ date: 5, month: 0 }, { date: 6, month: 0 }),
            new DayTimeRange({ date: 6, month: 0 }, { date: 7, month: 0 }),
            new DayTimeRange({ date: 7, month: 0 }, { date: 8, month: 0 }),
            new DayTimeRange({ date: 8, month: 0 }, { date: 9, month: 0 }),
            new DayTimeRange({ date: 9, month: 0 }, { date: 10, month: 0 }),
            new DayTimeRange({ date: 10, month: 0 }, { date: 11, month: 0 }),
            new DayTimeRange({ date: 11, month: 0 }, { date: 12, month: 0 }),
            new DayTimeRange({ date: 12, month: 0 }, { date: 13, month: 0 }),
            new DayTimeRange({ date: 13, month: 0 }, { date: 14, month: 0 }),
            new DayTimeRange({ date: 14, month: 0 }, { date: 15, month: 0 }),
            new DayTimeRange({ date: 15, month: 0 }, { date: 16, month: 0 }),
            new DayTimeRange({ date: 16, month: 0 }, { date: 17, month: 0 }),
            new DayTimeRange({ date: 17, month: 0 }, { date: 18, month: 0 }),
            new DayTimeRange({ date: 18, month: 0 }, { date: 19, month: 0 }),
            new DayTimeRange({ date: 19, month: 0 }, { date: 20, month: 0 }),
            new DayTimeRange({ date: 20, month: 0 }, { date: 21, month: 0 }),
            new DayTimeRange({ date: 21, month: 0 }, { date: 22, month: 0 }),
            new DayTimeRange({ date: 22, month: 0 }, { date: 23, month: 0 }),
            new DayTimeRange({ date: 23, month: 0 }, { date: 24, month: 0 }),
            new DayTimeRange({ date: 24, month: 0 }, { date: 25, month: 0 }),
            new DayTimeRange({ date: 25, month: 0 }, { date: 26, month: 0 }),
            new DayTimeRange({ date: 26, month: 0 }, { date: 27, month: 0 }),
            new DayTimeRange({ date: 27, month: 0 }, { date: 28, month: 0 }),
            new DayTimeRange({ date: 28, month: 0 }, { date: 29, month: 0 }),
            new DayTimeRange({ date: 29, month: 0 }, { date: 30, month: 0 }),
            new DayTimeRange({ date: 30, month: 0 }, { date: 31, month: 0 }),
            new DayTimeRange({ date: 31, month: 0 }, { date: 1, month: 1 }),
            new DayTimeRange({ date: 1, month: 1 }, { date: 2, month: 1 }),
            new DayTimeRange({ date: 2, month: 1 }, { date: 3, month: 1 }),
            new DayTimeRange({ date: 3, month: 1 }, { date: 4, month: 1 }),
            new DayTimeRange({ date: 4, month: 1 }, { date: 5, month: 1 }),
            new DayTimeRange({ date: 5, month: 1 }, { date: 6, month: 1 }),
            new DayTimeRange({ date: 6, month: 1 }, { date: 7, month: 1 }),
            new DayTimeRange({ date: 7, month: 1 }, { date: 8, month: 1 }),
            new DayTimeRange({ date: 8, month: 1 }, { date: 9, month: 1 }),
            new DayTimeRange({ date: 9, month: 1 }, { date: 10, month: 1 }),
            new DayTimeRange({ date: 10, month: 1 }, { date: 11, month: 1 }),
            new DayTimeRange({ date: 11, month: 1 }, { date: 12, month: 1 }),
            new DayTimeRange({ date: 12, month: 1 }, { date: 13, month: 1 }),
            new DayTimeRange({ date: 13, month: 1 }, { date: 14, month: 1 }),
            new DayTimeRange({ date: 14, month: 1 }, { date: 15, month: 1 }),
            new DayTimeRange({ date: 15, month: 1 }, { date: 16, month: 1 }),
            new DayTimeRange({ date: 16, month: 1 }, { date: 17, month: 1 }),
            new DayTimeRange({ date: 17, month: 1 }, { date: 18, month: 1 }),
            new DayTimeRange({ date: 18, month: 1 }, { date: 19, month: 1 }),
            new DayTimeRange({ date: 19, month: 1 }, { date: 20, month: 1 }),
            new DayTimeRange({ date: 20, month: 1 }, { date: 21, month: 1 }),
            new DayTimeRange({ date: 21, month: 1 }, { date: 22, month: 1 }),
            new DayTimeRange({ date: 22, month: 1 }, { date: 23, month: 1 }),
            new DayTimeRange({ date: 23, month: 1 }, { date: 24, month: 1 }),
            new DayTimeRange({ date: 24, month: 1 }, { date: 25, month: 1 }),
            new DayTimeRange({ date: 25, month: 1 }, { date: 26, month: 1 }),
            new DayTimeRange({ date: 26, month: 1 }, { date: 27, month: 1 }),
            new DayTimeRange({ date: 27, month: 1 }, { date: 28, month: 1 }),
            new DayTimeRange({ date: 28, month: 1 }, { date: 1, month: 2 }),

            new DayTimeRange({ date: 1, month: 2 }, { date: 2, month: 2 }),
            new DayTimeRange({ date: 2, month: 2 }, { date: 3, month: 2 }),
            new DayTimeRange({ date: 3, month: 2 }, { date: 4, month: 2 }),
            new DayTimeRange({ date: 4, month: 2 }, { date: 5, month: 2 }),
            new DayTimeRange({ date: 5, month: 2 }, { date: 6, month: 2 }),
            new DayTimeRange({ date: 6, month: 2 }, { date: 7, month: 2 }),
            new DayTimeRange({ date: 7, month: 2 }, { date: 8, month: 2 }),
            new DayTimeRange({ date: 8, month: 2 }, { date: 9, month: 2 }),
            new DayTimeRange({ date: 9, month: 2 }, { date: 10, month: 2 }),
            new DayTimeRange({ date: 10, month: 2 }, { date: 11, month: 2 }),
            new DayTimeRange({ date: 11, month: 2 }, { date: 12, month: 2 }),
            new DayTimeRange({ date: 12, month: 2 }, { date: 13, month: 2 }),
            new DayTimeRange({ date: 13, month: 2 }, { date: 14, month: 2 }),
            new DayTimeRange({ date: 14, month: 2 }, { date: 15, month: 2 }),
            new DayTimeRange({ date: 15, month: 2 }, { date: 16, month: 2 }),
            new DayTimeRange({ date: 16, month: 2 }, { date: 17, month: 2 }),
            new DayTimeRange({ date: 17, month: 2 }, { date: 18, month: 2 }),
            new DayTimeRange({ date: 18, month: 2 }, { date: 19, month: 2 }),
            new DayTimeRange({ date: 19, month: 2 }, { date: 20, month: 2 })
        ];

        for (let i = 0; i < 360; i++) {
            let item = this.add(new ZodiacAngleSpirit(i + 1, timeRanges[i]));
            item.degree = item.icon = `${i + 1}°`;
            item.zodiac = zodiacs.collection[Math.floor(i / 30)];
            item.zodiac.angleSpirits.push(item);
        }
    }
}